### ISSUE TITLE
Need an option to totally disable auto-double conversion

### ISSUE THREAD

**Issue by alenwesker** [ashaduri/csv-parser#1]
I have a CSV, contains some int data. CSV-parser parses them to double.
It's Ok, but we need them to stay as simple strings for further complex value evaluation.
I change a little bit of the code locally to handle the problem temporarily.
So, an option to make it able to disable the auto conversion may be a good idea.

**Comment by ashaduri** [comment]
You can use `Csv::CellStringReference` or `Csv::CellStringValue` instead of `Csv::CellReference` to avoid parsing to double, although you can still get the string even with `Csv::CellReference` by using `Csv::CellReference::getCleanString()`.

**Comment by alenwesker** [comment]
Oh, yeah, thank you for replying, I will try what you said.

**Comment by alenwesker** [comment]
Tested what you said, works. Thank you for your library, I found it on github's awesome c++ page. I've tested 3 libs before using yours, either suffer for this or that problems.  
Your lib is good, program's salute.
